_wandb:
    value:
        cli_version: 0.21.1
        e:
            l1k4qd45tar5r00obrwobjllvqs5ctgl:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "8589934592"
                args:
                    - app.main:app
                    - --reload
                    - --port
                    - "8000"
                codePath: fastapi/bin/uvicorn
                codePathLocal: fastapi/bin/uvicorn
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "205020090368"
                email: aye2904@gmail.com
                executable: /Users/andreabassick/Desktop/SeniorProject/my_fastapi_backend_repo/fastapi/bin/python3.13
                git:
                    commit: 9f15bcce84f04c94ade6989ce56055a0c1187d36
                    remote: https://github.com/aye-nyeinSan/my_fastapi_backend_repo.git
                host: RubiLing.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/andreabassick/Desktop/SeniorProject/my_fastapi_backend_repo/fastapi/bin/uvicorn
                python: CPython 3.13.6
                root: /Users/andreabassick/Desktop/SeniorProject/my_fastapi_backend_repo
                startedAt: "2025-09-02T08:45:42.613516Z"
                writerId: l1k4qd45tar5r00obrwobjllvqs5ctgl
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
