name: Retrain Model on feedback data using WandB
on:
    workflow_dispatch:
         # You can add inputs here if you want to pass parameters from your FastAPI app
    # inputs:
    #   dataset_path:
    #     description: 'Path to the dataset for retraining'
    #     required: false
    #     default: 'data/feedback.csv'

    

jobs:
    
    install_dependencies:
        outputs: 
          deps_cache_key : ${{ steps.cache_key.outputs.CACHE_KEY }}

        runs-on: ubuntu-latest
        steps: 
          - name: checkout repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.11'

          - name : Get pip cache directory
            shell: bash
            run: |
              echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

          - name : Get Cache Key
            id: cache_key
            shell: bash
            run: |
              echo "CACHE_KEY=${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}" >> $GITHUB_OUTPUT
              
          - name: Caching dependencies
            uses: actions/cache@v4
            id: pip-cache
            with:
              path: ${{env.PIP_CACHE_DIR}}
              key: ${{ steps.cache_key.outputs.CACHE_KEY }}
          
         
            
          - name: Install dependencies
            if: ${{ steps.pip-cache.outputs.cache-hit != 'true' }}  
            run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
    login_wandb:
        needs: install_dependencies
        runs-on: ubuntu-latest
        steps:
             - name: checkout repository
               uses: actions/checkout@v4

             - name: Set up Python
               uses: actions/setup-python@v2
               with:
                 python-version: '3.11'

             - name : Get pip cache directory
               shell: bash
               run: |
                 echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

             - name : Get Cache Key
               id: cache_key
               shell: bash
               run: |
                 echo "CACHE_KEY=${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}" >> $GITHUB_OUTPUT
              
             - name: Caching dependencies
               uses: actions/cache@v4
               id: pip-cache
               with:
                path: ${{env.PIP_CACHE_DIR}}
                key: ${{ steps.cache_key.outputs.CACHE_KEY }}

             - name: Login WandB
               env:
                 WANDB_API_KEY: ${{ secrets.WANDB_LOGIN_KEY }}
               run: |
                     wandb login $WANDB_API_KEY
                     echo "Logged into WandB"
    # retrain_model:
    #     runs-on: ubuntu-latest
    #     needs: [install_dependencies,login_wandb]
    #     steps:
    #         - name: Retrain model
    #           env:
    #             WANDB_API_KEY: ${{ secrets.WANDB_LOGIN_KEY }}
    #           run: |
    #                 papermill "notebooks/ExploreWeights&Biases.ipynb" \
    #                  "notebooks/retrained_sentiment_model.ipynb" \
    #                  --log-output \
    #                  --kernel python3 
            
        
              