name: Retrain Model on feedback data using WandB
on:
    workflow_dispatch:
         # You can add inputs here if you want to pass parameters from your FastAPI app
    # inputs:
    #   dataset_path:
    #     description: 'Path to the dataset for retraining'
    #     required: false
    #     default: 'data/feedback.csv'

jobs:
    install_dependencies:
        runs-on: ubuntu-latest
        steps: 
          - name: checkout repository
            uses: actions/checkout@v4
          
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.11'
                cache: 'pip'
            
          - name: Install dependencies
            run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
    login_wandb:
        needs: install_dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Login WandB
              env:
                WANDB_API_KEY: ${{ secrets.WANDB_LOGIN_KEY }}
              run: |
                    wandb login $WANDB_API_KEY
                    echo "Logged into WandB"
    retrain_model:
        runs-on: ubuntu-latest
        needs: [install_dependencies,login_wandb]
        steps:
            - name: Retrain model
              env:
                WANDB_API_KEY: ${{ secrets.WANDB_LOGIN_KEY }}
              run: |
                    papermill "notebooks/ExploreWeights&Biases.ipynb" \
                     "notebooks/retrained_sentiment_model.ipynb" \
                     --log-output \
                     --kernel python3 
            
        
              