name: Retrain Model on feedback data using WandB
on:
    workflow_dispatch:
      inputs:
        dataset_path:
          description: 'Path to the dataset for retraining'
          required: true  # must provide a value

    

jobs:
    
    training_model:
        outputs: 
          deps_cache_key : ${{ steps.cache_key.outputs.CACHE_KEY }}

        runs-on: ubuntu-latest
        steps: 
          - name: checkout repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.11'


          - name : Get pip cache directory
            shell: bash
            run: |
              echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV
              echo " dataset path inputs= ${{ github.event.inputs.dataset_path }}"

          - name : Get Cache Key
            id: cache_key
            shell: bash
            run: |
              echo "CACHE_KEY=${{ runner.os }}-pip-${{ hashFiles('**/ml-requirements.txt') }}" >> $GITHUB_OUTPUT
              
          - name: Caching dependencies
            uses: actions/cache@v4
            id: pip-cache
            with:
              path: ${{env.PIP_CACHE_DIR}}
              key: ${{ steps.cache_key.outputs.CACHE_KEY }}
         
            
          - name: Install dependencies
            run: |
                  python -m pip install --upgrade pip
                  pip install -r ml-requirements.txt
            
  
          - name: Login WandB
            env:
              WANDB_API_KEY: ${{ secrets.WANDB_LOGIN_KEY }}
            run: |
                wandb login $WANDB_API_KEY
                echo "Logged into WandB"
                
          - name: Retrain model
            env:
                WANDB_API_KEY: ${{ secrets.WANDB_LOGIN_KEY }}
            run: |
                  gdown https://drive.google.com/uc?id=1YxLA_B9yKP5qIINrpmRvY7zg8TqfjZnz -O notebooks/MyanSen_Model_Training.ipynb
                  papermill "notebooks/MyanSen_Model_Training.ipynb" \
                  "notebooks/retrained_sentiment_model.ipynb" \
                  -p dataset_path "${{ github.event.inputs.dataset_path }}"\
                  --log-output \
                  --kernel python3 

           
            
        
              